In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")
import json

In [18]:
orig_data = pd.read_csv('data/original_data/newsroom-human-eval.csv')
print(orig_data.shape)
# unique ids
print("Unique ids: ", orig_data['ArticleID'].nunique())
orig_data.head()

(1260, 9)
Unique ids:  60

,ArticleID,System,ArticleText,SystemSummary,ArticleTitle,CoherenceRating,FluencyRating,InformativenessRating,RelevanceRating
0,2140,fragments,A worker sets up a polling station the morning...,John Avlon voter turnout in the is a sign of a...,Why has GOP turnout taken a dive?,2,2,2,2
1,2140,fragments,A worker sets up a polling station the morning...,John Avlon voter turnout in the is a sign of a...,Why has GOP turnout taken a dive?,4,5,4,4
2,2140,fragments,A worker sets up a polling station the morning...,John Avlon voter turnout in the is a sign of a...,Why has GOP turnout taken a dive?,2,3,2,3
3,2140,textrank,A worker sets up a polling station the morning...,"In New Hampshire , the same dynamic applied --...",Why has GOP turnout taken a dive?,4,5,4,5
4,2140,textrank,A worker sets up a polling station the morning...,"In New Hampshire , the same dynamic applied --...",Why has GOP turnout taken a dive?,3,2,3,2

In [13]:
print(orig_data['ArticleText'][1])
print()
print(orig_data['SystemSummary'][1])

A worker sets up a polling station the morning of the GOP primary in Florida. Fewer voters than expected turned out.</p><p>Editor&#x27;s note: John Avlon is a CNN contributor and senior political columnist for Newsweek and The Daily Beast. He is co-editor of the book &quot;Deadline Artists: America&#x27;s Greatest Newspaper Columns.&quot;</p><p>(CNN) -- Beneath Rick Santorum&#x27;s stunning three-state sweep on Tuesday stands another stubborn sign of dissatisfaction with the status quo: Republican turnout is down.</p><p>I&#x27;m talking embarrassingly, disturbingly, hey-don&#x27;t-you-know-it&#x27;s-an-election-year bad. It is a sign of a serious enthusiasm gap among the rank and file, and a particularly bad omen for Mitt Romney and the GOP in the general election.</p><p>Here&#x27;s the tale of the tape, state by state, beginning with Tuesday night: Minnesota had just more than 47,000 people turn out for its caucuses this year -- four years ago it was nearly 63,000 -- and Romney came in first, not a distant third as he did Tuesday night. In Colorado, more than 70,000 people turned out for its caucus in 2008 -- but in 2012 it was 65,000. And Missouri -- even making a generous discount for the fact that this was an entirely symbolic contest -- had 232,000 people turn out, less than half the number who did four years ago.</p><p>Even with months of pre-primary hype and attention solely devoted to the Republican field, turnout in this election cycle essentially flat-lined. In Iowa, a little more than 121,000 people voted, compared with nearly 119,000 four years before, when action in the Democratic caucuses absorbed most of the attention.</p><p>In New Hampshire, the same dynamic applied -- 245,000 voters turned out in 2012, compared with 241,000 four years before, despite Republicans being the only game in town and independents making up 47% of the total turnout in 2012, according to CNN exit polls. Take out the independent voters and you&#x27;ve got a deep net decline.</p><p>Always proudly rebellious, South Carolina has been the great outlier in this election cycle. With Newt Gingrich making an all-out push for conservatives in a conservative state, turnout was up almost 150,000 over four years before.</p><p>But in Florida, the decline became unmistakable. Maybe it decreased because the Romney and Gingrich campaigns, plus super PACS, spent more than $18 million in the Sunshine State on TV ads, of which 93% were negative in the last week alone, according to the Campaign Media Analysis Group. After all, negative ads depress turnout. But after all the mud was thrown, 1.6 million people turned out in the nation&#x27;s fourth largest state, which might sound impressive until you compare it with the nearly 2 million who turned out in 2008.</p><p>Nevada was even worse, with 32,894 people turning out to vote in a state with more than 465,000 registered Republicans. Four years before, more than 44,300 participated in the caucus. Turnout was down more than 25% despite the GOP caucuses being the only game in town. Party officials were expecting a turnout of more than 70,000.</p><p>All this should be a wake-up call for the GOP. Despite an enormous amount of national media attention devoted to each of the states to date, the response has been a notable yawn among the Republican rank and file.</p><p>The turnout numbers are even worse when you compare them with the number of registered Republicans in each state that has voted to date.</p><p>The caucuses in particular bring out an unrepresentative sample of a state&#x27;s Republican Party. For all the grass-roots romanticism, there has got to be a better way to pick a presidential nominee.</p><p>But the news is worst for Romney, long the presumptive front-runner in a party that tends to reward the man next in line.</p><p>&quot;Reluctantly Romney&quot; could be a bumper sticker, even for his supporters. The former Massachusetts governor has found it difficult to climb above 35% in national polls, meaning that a majority of Republicans still support someone else in a notably weak field. His vote margins and totals lag behind those of four years before, when he lost the nomination to John McCain in a crowded and comparatively competent field, although Minnesota is the first state he won in &#x27;08 and lost in 2012.</p><p>You reap what you sow, and part of the reason turnout is down is directly related to the problem of polarization. The Republican Party is more ideologically polarized than at any time in recent history. Therefore, it put up more purely right-wing candidates than it did four years before, when center-right leaders such as McCain and Rudy Giuliani were also in the race. A bigger tent inspired bigger turnout.</p><p>But the other reason is simple dissatisfaction with the candidates.</p><p>Republicans seem united in their anger against the president -- like the Democrats in 2004 -- but they are uninspired by their options. Draft movements for fantasy candidates ranging from Chris Christie to Mitch Daniels to Paul Ryan and even Jeb Bush have started and failed. Some party leaders show more enthusiasm for a hypothetical 2016 crop of candidates, including Marco Rubio and Bobby Jindal, than they do for the flawed choices before them in this election. Divided and dispirited is an odd place for the Republican Party to be so soon after the enthusiasms of the 2010 tea party-driven election.</p><p>The bottom line is that voter turnout matters. And what should be most troubling for Republicans is that this enthusiasm gap among the conservative base is accompanied by a lack of candidates who might appeal to independents and centrist swing voters in the general election. It is a double barrel of bad news for the Republican Party. The numbers can be spun and rationalized by professional partisan operatives all day long, but the fact remains -- voters just aren&#x27;t turning out to cast their votes for this crop of conservative candidates in 2012.</p><p>Follow CNN Opinion on Twitter.</p><p>Join the conversation on Facebook.</p><p>The opinions expressed in this commentary are solely those of John Avlon.

John Avlon voter turnout in the is a sign of a serious enthusiasm gap among the rank and file , a bad omen for the GOP .

In [19]:
data = json.loads(open('data/newsroom.json').read())
for idx, annot in enumerate(data['annotations'], 1):
    print(f"#{idx}")
    print(f" - Metrics: {annot['metric']}")
    print(f" - Prompt: {annot['prompt']}")
    print()
    
    with open(f"prompts/{annot['metric']}_prompt.txt", "w", encoding="utf-8") as f:
        f.write(annot['prompt'])

#1
 - Metrics: Informativeness
 - Prompt: On a scale of 1 (low) to 5 (high), how well does the summary capture the key points of the article?

{{ instance }}

#2
 - Metrics: Relevance
 - Prompt: On a scale of 1 (low) to 5 (high), are the details provided by the summary consistent with details in the article?

{{ instance }}

#3
 - Metrics: Fluency
 - Prompt: On a scale of 1 (low) to 5 (high), are the individual sentences of the summary well-written and grammatical?

{{ instance }}

#4
 - Metrics: Coherence
 - Prompt: On a scale of 1 (low) to 5 (high), do phrases and sentences of the summary fit together and make sense collectively?

{{ instance }}

In [9]:
data['instances'][0]

{'id': 1,
 'instance': '### Generated Summary\n\ncollection of all usatoday.com coverage of war of chenda , including articles , videos , photos , and quotes . and videos .\n\n### Source Article\n\n\'16 & Pregnant\' Couple Arrested, Toddler Taken Into Custody\nJacksonville, Ark., police arrested reality TV stars Joshua Rendon and Ebony Jackson-Rendon this week after police found their filthy home contained drug paraphernalia and synthetic marijuana. The state took custody of the couple\'s young child.</p><p>The 19-year-olds, who currently live at the Little Rock Air Force base, appeared on the first season of MTV\'s "16 and Pregnant" in a plot line that included Joshua Rendon enlisting in the Air Force.</p><p>Mug shots of Ebony Jackson-Rendon and Joshua Rendon provided by Jacksonville, Ark., Police Department.</p><p>When the police executed a search warrant of the Rendons\' home Tuesday, detectives described its condition as "deplorable. According to the police report, "Every room inside the residence had human and dog feces on the floors, walls and clothing."</p><p>The house was full of flies and maggots, the police report stated. Photos show dirty diapers, cigarette buds and trash littering filthy carpets in the couple\'s home.</p><p>Amid the filth was the couple\'s 2-year-old daughter. The Arkansas Department of Human Services stepped in and took custody of the toddler.</p><p>The teen parents face felony charges of maintaining a drug premises and making unauthorized use of another\'s property to abet a crime. They face misdemeanor charges of endangering the welfare of a minor, possession of drug paraphernalia and possession of a controlled substance.</p><p>The two were released from jail on an $8,000 bond, but it\'s not known if they have regained custody of their daughter, ABC Affiliate KATV reported.</p><p>Military officials won\'t comment on whether Joshua Rendon will be disciplined, according to KATV\'s report.</p><p>The couple is scheduled to appear in court Oct. 6.',
 'annotations': {'Informativeness': {'mean_human': 2.67,
   'individual_human_scores': [4, 3, 1]},
  'Relevance': {'mean_human': 3.33, 'individual_human_scores': [4, 5, 1]},
  'Fluency': {'mean_human': 3.67,
   'majority_human': 3,
   'individual_human_scores': [3, 5, 3]},
  'Coherence': {'mean_human': 3.67,
   'majority_human': 4,
   'individual_human_scores': [4, 4, 3]}}}

In [10]:
data['instances'][0]['instance']

'### Generated Summary\n\ncollection of all usatoday.com coverage of war of chenda , including articles , videos , photos , and quotes . and videos .\n\n### Source Article\n\n\'16 & Pregnant\' Couple Arrested, Toddler Taken Into Custody\nJacksonville, Ark., police arrested reality TV stars Joshua Rendon and Ebony Jackson-Rendon this week after police found their filthy home contained drug paraphernalia and synthetic marijuana. The state took custody of the couple\'s young child.</p><p>The 19-year-olds, who currently live at the Little Rock Air Force base, appeared on the first season of MTV\'s "16 and Pregnant" in a plot line that included Joshua Rendon enlisting in the Air Force.</p><p>Mug shots of Ebony Jackson-Rendon and Joshua Rendon provided by Jacksonville, Ark., Police Department.</p><p>When the police executed a search warrant of the Rendons\' home Tuesday, detectives described its condition as "deplorable. According to the police report, "Every room inside the residence had human and dog feces on the floors, walls and clothing."</p><p>The house was full of flies and maggots, the police report stated. Photos show dirty diapers, cigarette buds and trash littering filthy carpets in the couple\'s home.</p><p>Amid the filth was the couple\'s 2-year-old daughter. The Arkansas Department of Human Services stepped in and took custody of the toddler.</p><p>The teen parents face felony charges of maintaining a drug premises and making unauthorized use of another\'s property to abet a crime. They face misdemeanor charges of endangering the welfare of a minor, possession of drug paraphernalia and possession of a controlled substance.</p><p>The two were released from jail on an $8,000 bond, but it\'s not known if they have regained custody of their daughter, ABC Affiliate KATV reported.</p><p>Military officials won\'t comment on whether Joshua Rendon will be disciplined, according to KATV\'s report.</p><p>The couple is scheduled to appear in court Oct. 6.'

In [15]:
instances = data["instances"]


# Flatten the nested structure for easier analysis
flattened_data = []
for instance in instances:
    row = {
        "id": instance["id"],
        "instance": instance["instance"],
        #informativeness
        "informativeness_mean": instance['annotations']["Informativeness"]["mean_human"],
        "informativeness_scores": instance['annotations']["Informativeness"]["individual_human_scores"],
        #relevance
        "relevance_mean": instance['annotations']["Relevance"]["mean_human"],
        "relevance_scores": instance['annotations']["Relevance"]["individual_human_scores"],
        #fluency
        "fluency_mean": instance['annotations']["Fluency"]["mean_human"],
        "fluency_scores": instance['annotations']["Fluency"]["individual_human_scores"],
        #coherence
        "coherence_mean": instance['annotations']["Coherence"]["mean_human"],
        "coherence_scores": instance['annotations']["Coherence"]["individual_human_scores"],
    }
    flattened_data.append(row)


df = pd.DataFrame(flattened_data)
#df['n_annotations'] = df['individual_human_scores'].apply(len)

print(df.shape)
df.head()

(420, 10)

,id,instance,informativeness_mean,informativeness_scores,relevance_mean,relevance_scores,fluency_mean,fluency_scores,coherence_mean,coherence_scores
0,1,### Generated Summary\n\ncollection of all usa...,2.67,"[4, 3, 1]",3.33,"[4, 5, 1]",3.67,"[3, 5, 3]",3.67,"[4, 4, 3]"
1,2,"### Generated Summary\n\nJacksonville , Ark. ,...",4.33,"[4, 5, 4]",4.67,"[4, 5, 5]",4.33,"[3, 5, 5]",4.00,"[3, 5, 4]"
2,3,"### Generated Summary\n\nJacksonville , Ark. ,...",4.00,"[3, 5, 4]",4.00,"[4, 5, 3]",4.00,"[4, 5, 3]",4.33,"[4, 5, 4]"
3,4,### Generated Summary\n\nstars joshua rendon 1...,3.00,"[3, 3, 3]",3.67,"[3, 4, 4]",3.00,"[3, 2, 4]",2.67,"[3, 2, 3]"
4,5,### Generated Summary\n\njoshua rendon and ebo...,4.00,"[3, 4, 5]",3.33,"[4, 3, 3]",3.67,"[4, 3, 4]",3.67,"[3, 4, 4]"

In [16]:
df['instance'][0]

'### Generated Summary\n\ncollection of all usatoday.com coverage of war of chenda , including articles , videos , photos , and quotes . and videos .\n\n### Source Article\n\n\'16 & Pregnant\' Couple Arrested, Toddler Taken Into Custody\nJacksonville, Ark., police arrested reality TV stars Joshua Rendon and Ebony Jackson-Rendon this week after police found their filthy home contained drug paraphernalia and synthetic marijuana. The state took custody of the couple\'s young child.</p><p>The 19-year-olds, who currently live at the Little Rock Air Force base, appeared on the first season of MTV\'s "16 and Pregnant" in a plot line that included Joshua Rendon enlisting in the Air Force.</p><p>Mug shots of Ebony Jackson-Rendon and Joshua Rendon provided by Jacksonville, Ark., Police Department.</p><p>When the police executed a search warrant of the Rendons\' home Tuesday, detectives described its condition as "deplorable. According to the police report, "Every room inside the residence had human and dog feces on the floors, walls and clothing."</p><p>The house was full of flies and maggots, the police report stated. Photos show dirty diapers, cigarette buds and trash littering filthy carpets in the couple\'s home.</p><p>Amid the filth was the couple\'s 2-year-old daughter. The Arkansas Department of Human Services stepped in and took custody of the toddler.</p><p>The teen parents face felony charges of maintaining a drug premises and making unauthorized use of another\'s property to abet a crime. They face misdemeanor charges of endangering the welfare of a minor, possession of drug paraphernalia and possession of a controlled substance.</p><p>The two were released from jail on an $8,000 bond, but it\'s not known if they have regained custody of their daughter, ABC Affiliate KATV reported.</p><p>Military officials won\'t comment on whether Joshua Rendon will be disciplined, according to KATV\'s report.</p><p>The couple is scheduled to appear in court Oct. 6.'